<?php
/*
Plugin Name: User Generator and Importer
Plugin URI: http://buffercode.com/
Description: Simple way to import or generate user name, password, email id and many more for wordpress using this plugin.
Version: 1.2.2
Author: vinoth06
Author URI: http://buffercode.com/
License: GPLv2
*/
ini_set("memory_limit","1024M");
ini_set("max_execution_time", "240");

add_action('admin_menu', 'bc_username_menu');
function bc_username_menu() {
	add_menu_page('user generator id', 'User Generator', 'administrator', __FILE__, 'bc_user_gen_settings');
	add_action( 'admin_init', 'bc_user_gen_register_settings' );
}

function bc_user_gen_register_settings() {
register_setting( 'bc-user-settings-group', 'bc_user_name' );
register_setting( 'bc-user-settings-group', 'bc_user_times' );	
register_setting( 'bc-user-settings-group', 'bc_user_email' );	
register_setting( 'bc-user-settings-group', 'bc_user_role' );	
register_setting( 'bc-user-settings-group', 'bc_user_email_domain' );	
}
function bc_user_gen_settings(){ 
$bc_user_role_value=get_option('bc_user_role');
global $bc_user_name_value,$bc_user_times_value,$bc_user_email_value,$bc_user_email_domain_value;
$bc_user_name_value=get_option('bc_user_name');
$bc_user_times_value=get_option('bc_user_times'); 
$bc_user_email_value=get_option('bc_user_email'); 
$bc_user_email_domain_value=get_option('bc_user_email_domain'); 
?>
<div class="wrap">
<h2>User Generator</h2>
<?php if( isset($_GET['settings-updated']) ) { 
$flag=1;
if(empty($bc_user_name_value) || empty($bc_user_times_value) || empty($bc_user_email_value) ||empty($bc_user_email_domain_value))
{$flag=2;}
for($i=1;$i<=$bc_user_times_value;$i++){
$bc_user_name_values=$bc_user_name_value.$i;
$bc_user_email_values=$bc_user_email_value.$i.'@'.$bc_user_email_domain_value;
$role=$bc_user_role_value;
$user_id = username_exists( $bc_user_name_values );
if ( !$user_id and email_exists($bc_user_email_values) == false ) {
	$userarray=array('user_login' => $bc_user_name_values,
								'user_pass' => $bc_user_name_values,
								'user_email'=>$bc_user_email_values,
								'first_name'=>$bc_user_name_values,
								'role'=>$role );
								
	$user_id = wp_insert_user($userarray) ;

} else {
	$flag=0;
}
}
if($flag==1){?>

    <div id="message" class="updated fade">
        <p><strong><?php _e('Around '. $bc_user_times_value.' User(s) Registered...','buffercode_random_captcha') ?></strong></p>
    </div>
<?php }elseif($flag==2){ ?>	
	<div id="message" class="error">
	 <p><strong><?php _e('Please fill all details...','buffercode_random_captcha') ?></strong></p>
    </div>
<?php }else{ ?>	
	<div id="message" class="error">
	 <p><strong><?php _e('User name or mail id already exist...','buffercode_random_captcha') ?></strong></p>
    </div>

<?php
}
} ?>

<form method="post" action="options.php">
<?php settings_fields( 'bc-user-settings-group' ); ?>
    <?php do_settings_sections( 'bc-user-settings-group' );?>
<table class="form-table">
        <tr valign="top">
        <th scope="row"><?php _e("<b>User Name Starts with</b>",'buffercode_captcha'); ?></th>
        <td>
		<input  type="text" name="bc_user_name" maxlength="10" value="<?php echo $bc_user_name_value; ?>"/> <b>[Generated by appending numbers eg. if input is alex, then user name will be alex1,alex2,alex3... upto number of time execution] </b>
		</td>
        </tr>
		  <tr valign="top">
        <th scope="row"><?php _e("<b>Number of time execute</b>",'buffercode_captcha'); ?></th>
        <td>
		<input  type="text" name="bc_user_times" maxlength="2" onkeypress="return isNumber(event)" value="<?php echo $bc_user_times_value; ?>"/> <b>[ Try entring below 50, else you may face Timeout issue]</b>
		</td>

        </tr>
		<tr valign="top">
        <th scope="row"><?php _e("<b>Email ID</b>",'buffercode_captcha'); ?></th>
        <td>
		<input  type="text" name="bc_user_email" maxlength="52" value="<?php echo $bc_user_email_value; ?>"/> <b>[No @ and domain name - eg, alex only not alex@alex.com]</b>
		</td>
        </tr>
		<tr valign="top">
        <th scope="row"><?php _e("<b>Email Domain Name</b>",'buffercode_captcha'); ?></th>
        <td>
		<input  type="text" name="bc_user_email_domain" maxlength="52" value="<?php echo $bc_user_email_domain_value ?>"/> <b>[ No user id only domain name with out @ eg, alex.com]</b>
		</td>
        </tr>
		<tr valign="top">
        <th scope="row"><?php _e("<b>Role</b>",'buffercode_captcha'); ?></th>
        <td>
		<select name="bc_user_role">
		<option value="administrator" <?php echo selected('administrator',$bc_user_role_value); ?>>Administrator</option>
		<option value="editor" <?php echo selected('editor',$bc_user_role_value); ?>>Editor</option>
		<option value="author" <?php echo selected('author',$bc_user_role_value); ?>>Author</option>
		<option value="contributor" <?php echo selected('contributor',$bc_user_role_value); ?>>Contributor</option>
		<option value="subscriber" <?php echo selected('subscriber',$bc_user_role_value); ?>>Subscriber</option>
		</select>
		</td>
        </tr>
		</table>
		<input type="hidden" name="mode_gen" value="submit1">
	    <?php submit_button(); ?>
			</form>
			<b>Note: Password will be same as the username</b>
		<hr width=50% align="left">
</div>
<script>
function isNumber(evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
    }
    return true;
}
</script>
<?php

////////////////////////////import starts//////////
	global $wpdb,$bc_post_message,$not_imported_usernames;

	$bc_metadata_fields       = array(
		'first_name','last_name','description','user_login', 'user_pass',
		'user_email', 'user_url', 'user_nicename',
		'display_name', 'nickname', 'role',
	);
  	if (isset($_POST['mode']) == "submit") {
	
		$bc_row_values = file($_FILES['csv_file']['tmp_name']);
	
		if ( is_array( $bc_row_values ) ) {
			$first = true;
			$not_imported_usernames = '';
			$flag = 0;
			$bc_import_mssg = "";
			foreach ( $bc_row_values as $row ) {
			if ( empty( $row ) ) {
					if ( $first )
						break;
					else
						continue;
				}

				if ( $first ) {
					$calumn_names = str_replace('"', '', $row);
					$headers = explode(",", $calumn_names);
					$first = false;
					continue;
				}

				// explode into values
				$arr_values = str_replace('"', '', $row);
				$arr_values = explode(",", $arr_values);
				
				// Separate user data from meta
				$userdata = $usermeta = array();
				
				foreach ( $arr_values as $ckey => $cvalue ) {
					$column_name = trim( $headers[$ckey] );
					$cvalue = trim( $cvalue );

					if ( empty( $cvalue ) )
						continue;

					if ( in_array( $column_name, $bc_metadata_fields ) ) 
						$userdata[$column_name] = $cvalue;
					else
						$usermeta[$column_name] = $cvalue;
					
				}
				if ( empty( $userdata ) )
					continue;
				
				if ( empty( $userdata['user_pass'] ) )
					$userdata['user_pass'] = wp_generate_password( 12, false );
				
				$userdata['user_login'] = strtolower($userdata['user_login']);
				$user_id = wp_insert_user( $userdata );
				
				// Is there an error?
				if ( is_wp_error( $user_id ) ) {
					$flag = 1;
					$not_imported_usernames  .= "<b>" . $userdata['user_login'] . ' : </b> ' ;
				}
				else {
					// If no error, let's update the user meta too!
					if ( $usermeta )
						foreach ( $usermeta as $metakey => $metavalue ) {
							$metavalue = maybe_unserialize( $metavalue );
							update_user_meta( $user_id, $metakey, $metavalue );
						}

					$user_ids[] = $user_id;
				}

			}	

			if( $flag == 1 ) {
				$bc_import_mssg = "Following user(s) are not imported as they are already registered in your website:<br />".$not_imported_usernames."<br>Except above " ;
			}
			
			$bc_post_message = "<div class='updated'>".$bc_import_mssg."All users/members appear to be have been imported successfully.</div>";
			
		} // end of 'if bc_row_values is array'
		else
			$bc_post_message = "<div class='updated' style='color: red'>It seems the file was not uploaded correctly.</div>";
	} 	// end of 'if mode is submit'
	

?>
<div class="wrap">	
	<?php echo $bc_post_message; ?>	
	<h2>Import Using CSV File</h2>
	<p>Please select the CSV file you want to import below.</p>
	
	<form action="" method="post" enctype="multipart/form-data">
		<input type="hidden" name="mode" value="submit">
		<input type="file" name="csv_file" />		
		<input type="submit" value="Register" />

		<br/>
		</form>
		<br><br>
		<a href="<?php echo plugins_url('import-data.csv', __FILE__); ?>" >Download Template File</a> | More information visit - <a href="http://buffercode.com">Buffercode.com</a>
		</div>
<?php
}
?>
